name: Issue report
description: Report an issue with the partc11e {PackageName} codebase.
title: "🧰 Issue report: "
labels: ["type: issue"]
body:
  - type: markdown
    attributes:
      value: "
        <img src='https://avatars.githubusercontent.com/u/89670397?s=400' align='left' width='60' height ='60' />
        Thank you for reporting an issue!

        All efforts to improve partic11e libraries are greatly appreciated.

        <br clear='left' />"
  - type: textarea
    attributes:
      id: description
      label: Describe the issue
      description: For the quickest resolution, please provide as much information as possible, explaining the context the issue occured in and what happened. For security related issues, please contact us at IntegerEleven.
      placeholder: Explain the context the issue occured in and what happened.
    validations:
      required: true
  - type: textarea
    attributes:
      id: expectation
      description: Describe what you expected to happen and/or what you think went wrong.
      placeholder: Describe what you expected to happen and/or what you think went wrong.
    validations:
      required: true
  - type: textarea
    attributes:
      id: reproduction
      label: Steps to reproduce the issue
      description: What are the steps we can follow to reproduce the issue?
      placeholder: Provide a step-by-step case of how we can reproduce the issue as clear and concise as possible.
  - type: input
    attributes:
      id: pkgv
      label: Package version
      description: What version of the partic11e {PackageName} module is being used?
  - type: input
    attributes:
      id: denov
      label: Deno version
      description: What version of Deno are you using?
  - type: markdown
    attributes:
      value: <br />
  - type: markdown
    attributes:
      value: By submitting this issue, I am contributing to the project and agree to follow this project's [Code of Conduct](https://github.com/partic11e/{PackageName}/blob/main/code_of_conduct.md).




