name: Issue report
description: Report an issue with partc11e code.
title: "📚 Docs issues report: "
labels: ["type: docs"]
body:
  - type: markdown
    attributes:
      value: "
        <img src='https://avatars.githubusercontent.com/u/89670397?s=400' align='left' width='80' height ='80' />
        Thank you for reporting a documentation issue!

        All efforts to improve partic11e libraries are greatly appreciated.

        <br clear='left' />"
  - type: textarea
    attributes:
      label: Describe the documentation issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: How should we resolve the documentation issue?
  - type: textarea
    attributes:
      id: reproduction
      label: Steps to reproduce the issue
      description: What are the steps we can follow to reproduce the issue?
      placeholder: Provide a step-by-step case of how we can reproduce the issue. Be as detailed and clear as possible.
  - type: input
    attributes:
      id: pkgv
      label: Package version
      description: What version of this partic11e module has the documentation issue?
      placeholder: >
        You can find this by importing the "VERSION" export from the module's root "mod.ts" and logging it to console.
  - type: markdown
    attributes:
      value: <br />
  - type: markdown
    attributes:
      value: By submitting this issue, I am contributing to the project and agree to follow this project's 
